import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Invite web community",
  description: "Generated by next",

  metadataBase: new URL("https://www.originsurvey124815.com/"),

  // (추가) 파비콘/애플 터치 아이콘
  icons: {
  icon: [{ url: "/grass_icon.png", type: "image/png", sizes: "32x32" }], // 필요 시 다중 사이즈 추가
  apple: [{ url: "/grass_icon.png", sizes: "180x180" }],
},

  // (추가) 오픈그래프(카톡/슬랙/페북) 미리보기
  openGraph: {
    title: "Invite web community",
    description: "Generated by create next app",
    url: "/",
    siteName: "watch out your hair",
    images: [{ url: "/skybackground_icon.png", width: 1200, height: 630 }],
    type: "website",
    locale: "ko_KR",
  },

  // (추가) 트위터 카드 미리보기
  twitter: {
    card: "summary_large_image",
    title: "Create Next App",
    description: "Generated by create next app",
    images: ["/skybackground_icon.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
